### ISSUE TITLE
AutoPublishAlias is not triggered for environment variable changes

### ISSUE THREAD

**Issue by cakepietoast** [awslabs/serverless-application-model#1305]
**Description:**

Changing or adding/removing environment variables for a function does not cause a new version to be published when using `AutoPublishAlias`. 

**Steps to reproduce the issue:**
1. Deploy a SAM template with an `AWS::Serverless::Function` resource, with `AutoPublishAlias` set, and including an environment variable:  
```
HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: live
      Environment:
        Variables:
          TestKey: TestVal1
```  
2. Change `TestVal1` to `TestVal2`.  
3. Run sam deploy . 

**Observed result:**
The lambda function is updated with the new environment variable, but no new version is published, and the defined alias still points to the last published version.

**Expected result:**
A new function version is published, and the defined alias is updated to point to it.

**Comment by keetonian** [comment]
If the lambda function is invoked, does it have the old or new value for the environment variable?

**Comment by keetonian** [comment]
It looks like we can add the `Environment` dictionary to the hash that gets computed to determine if a new version needs to be published.

Section of code to update: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapi

**Comment by cakepietoast** [comment]
When invoking via api gateway, the "old" version gets invoked.

@szilveszter Did you paste the right url? Was expecting a link to a section of code but your link goes to documentation.

**Comment by dalumiller** [comment]
@cakepietoast  @keetonian This is similar to the #1267 where environment variables stored in Secrets Manager that are changed don't trigger a new version of the lambda.

**Comment by cakepietoast** [comment]
Closing this as it was resolved with #1310.

**Comment by heyjustcode** [comment]
@cakepietoast this still doesn't work if the environment variable change was due to an updated value of a referenced parameter
