### ISSUE TITLE
Providing a parameter gives an error. 

### ISSUE THREAD

**Issue by glangston83** [awslabs/serverless-application-model#33]
Had some trouble finding info on this, but I'm getting a validation error, when I supply a Parameter to the SAM template: 

aws cloudformation deploy --template-file template.yaml --stack-name stack2 --capabilities CAPABILITY_IAM

An error occurred (ValidationError) when calling the CreateChangeSet operation: Cannot specify UsePreviousValue on Parameters when ChangeSetType is CREATE

When I comment the Parameters, it creates fine.

Example code; 
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM template with API defined for Application. Swagger yaml included for API
Parameters:
  EnvParameter:
    Type: String
    Default: prod
    Description: Enter string for environment label of this deployment stack.

*I currently have no references to the parameter in my template for testing.

**Comment by sanathkr** [comment]
That's a known bug. When you add a default value to a parameter, `deploy` command doesn't pass it to CloudFormation. Try adding `--parameters EnvParameter=prod` to the command until this bug is fixed

**Comment by glangston83** [comment]
That works. The following yaml and CLI command worked for providing the parameters: 

--------
Parameters:
  EnvParameter:
    Type: String
    Description: Enter string for environment label of this deployment. Can represent a feature demo env, or a persistent testing environment.
------

aws cloudformation deploy --template-file template.yaml --stack-name stack2 --parameter-overrides EnvParameter=prod --capabilities CAPABILITY_IAM --profile sandbox

**Comment by mlabieniec** [comment]
Is there any update on when this may be fixed?

**Comment by sanathkr** [comment]
This is already fixed. https://github.com/aws/aws-cli/pull/2360

**Comment by bgenchel** [comment]
@sanathkr Just upgraded to the most recent version, still running into this issue.

**Comment by sbrickner** [comment]
This is still an issue. Deploying a SAM template with aws cloudformation deploy throws the following exception: 

An error occurred (ValidationError) when calling the CreateChangeSet operation: Cannot specify UsePreviousValue on Parameters when ChangeSetType is CREATE

The suggested fix of adding a default parameter does not work. Is there a work around?

**Comment by sanathkr** [comment]
@bgenchel, @sbrickner you are probably running into aws/aws-cli#2599 - which happens when you create stack for very first time.

Until we fix this bug, you can override the parameter explicitly when you add a new parameter with default value. Just once when you first update the stack. Afterwards, UsePreviousValue should work as expected

**Comment by Mohan1996** [comment]
For me, --parameters didn't work. I used --parameter-override. Im fairly new to AWS, so maybe AWS updated? Since this post was from Dec 2016.

Also, I got this issue when updating a stack. I'm on aws-cli 1.15.55. It fixed after I added a --parameter-override flag.

**Comment by raj-yadav9** [comment]
An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameters: [subnetIds] must have values

my command-    aws cloudformation deploy --template-file airflow.yaml --stack-name cloud-dev --parameter-overrides vpcId=123 SubnetIDs=subnet-2ezr3 , subnet-0yguft  Env=dev  --capabilities CAPABILITY_NAMED_IAM --profile staging

Can anyone help me with this error??

**Comment by chrisoverzero** [comment]
@raj-yadav9 It’s difficult to be sure without seeing the `Parameters` section of the template. That said, the error message indicates that it expects a parameter named `subnetIds`, but the command is specifying a parameter named `SubnetIDs`. Also, the value of `SubnetIDs` has spaces in it, which is probably confusing your shell. I suspect you’d prefer it to look something like this:

```
'subnetIds=subnet-2ezr3,subnet-0yguft'
```
