### ISSUE TITLE
Requires capabilities : [CAPABILITY_IAM]

### ISSUE THREAD

**Issue by avizaviz** [awslabs/serverless-application-model#51]
Hi,
I am trying to enable serverless deployment  with pipline and  cloudformation services  but failing to do so due to the following error:

My set of commands was:
```
c:\StackData\lambda>aws cloudformation package --template-file samTemplate.yml --s3-bucket lambdabiot --output-template-file outputTemplate.yml

Successfully packaged artifacts and wrote output template to file outputTemplate.yml.
Execute the following command to deploy the packaged template
aws cloudformation deploy --template-file c:\StackData\lambda\outputTemplate.yml --stack-name <YOUR STACK NAME>

c:\StackData\lambda>
c:\StackData\lambda>aws cloudformation deploy --template-file c:\StackData\lambda\outputTemplate.yml --stack-name ProdStack
Waiting for changeset to be created..

An error occurred (InsufficientCapabilitiesException) when calling the ExecuteChangeSet operation: Requires capabilities : [CAPABILITY_IAM]
```

**Comment by bfreis** [comment]
This error is a security related message: it happens when you try to create
a CloudFormation stack that includes the creation of IAM related resources.
You have to explicitly tell CloudFormation that you are OK with that.

To make it work, simply add the parameter --capabilities CAPABILITY_IAM to
your deploy command. That should solve the problem.

Cheers!

**Comment by sanathkr** [comment]
adding --capabilities should solve the problem. Let us know if it doesn't

**Comment by avizaviz** [comment]
Thanks

**Comment by manpenaloza** [comment]
I added the --capabilities CAPABILITY_IAM flag, but still get the the "Access denied" message in my console.

Here's the command I executed:
```javascript
 aws cloudformation deploy \
   --template-file serverless-output.yaml \
   --stack-name prod \
    --capabilities CAPABILITY_IAM
```

anytihing else that could cause this? thx for your support!

**Comment by davidwebstar34** [comment]
I have the exact same issue when I run create-stack for a cloudformation template that contains IAM policies.

`aws cloudformation create-stack --stack-name iam-stack --template-body file://./iam.yml --capabilities CAPABILITY_IAM --profile dev`

An error occurred (InsufficientCapabilitiesException) when calling the CreateStack operation: Requires capabilities : [CAPABILITY_NAMED_IAM]

**Comment by brysontyrrell** [comment]
@davidwebstar34 For you, switch `--capabilities CAPABILITY_IAM` to `--capabilities CAPABILITY_NAMED_IAM`. If you're not letting CloudFormation name your IAM resources you need to pass this capability.

**Comment by bgkpandurang** [comment]
i was also faced this issue ,fixed it by adding --capabilities CAPABILITY_IAM

**Comment by shetty-shruti** [comment]
adding --capabilities CAPABILITY_IAM worked for me too. Thanks

**Comment by ktajpuri** [comment]
adding **--capabilities CAPABILITY_IAM**   fixed the issue for me

**Comment by piyushchordia** [comment]
Add --capabilities CAPABILITY_NAMED_IAM
This should fix the issue

**Comment by C-Kenny** [comment]
Thanks @piyushchordia, `CAPABILITY_NAMED_IAM` worked for me also.

I ended up with a command like:

```
AWS_DEFAULT_PROFILE=role_name aws cloudformation create-stack --stack-name stack_name --template-url s3_url/template file --parameters file:///local_params.json --capabilities CAPABILITY_NAMED_IAM
```

**Comment by idolice** [comment]
i tried CAPABILITY_NAMED_IA & CAPABILITY_IAM, neither work for me, still get the same error message as avizaviz,  my cmd is:
aws cloudformation deploy --template-file target/output-sam.yaml --stack-name spring-boot-lambda --capabilities CAPABILITY_IAM
any suggesion?@sanathkr

**Comment by keetonian** [comment]
You may sometimes need multiple capabilities, like when working with nested stacks. You can add multiple capabilities by listing them (separated by a space):
`--capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND`

See https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html for more information about these capabilities. For most cases, you will only need one of these capabilities.

**Comment by abodero** [comment]
adding --capabilities CAPABILITY_IAM fixed the issue. thxs

**Comment by heijmerikx** [comment]
Ok, 'funny' this didn't work for me: 

`sam deploy --config-env default --profile myprofile –-capabilities CAPABILITY_IAM`

But this did: 

`sam deploy --config-env default --capabilities CAPABILITY_IAM --profile myprofile`

**Comment by citizenilustre** [comment]
> @davidwebstar34 For you, switch `--capabilities CAPABILITY_IAM` to `--capabilities CAPABILITY_NAMED_IAM`. If you're not letting CloudFormation name your IAM resources you need to pass this capability.

This was the solution for me, insetead of using CAPABILITY_IAM I used CAPABILITY_NAMED_IAM and it worked.
